Allow to find classes in multiple directories & improvements
yiisoft/classifier pull request #34
Opened 2023-06-20 16:33 UTC by rustamwin

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ✔️/❌
| Fixed issues  |

2023-06-20 16:41 UTC, xepozz requested changes

2023-06-20 16:41 UTC, xepozz commented on src/Classifier.php
> +            if (($this->targetClass !== null) && !is_subclass_of($className, $this->targetClass)) {
`targetClass` looks like a class that you exactly want to find, but actually it finds also inheriting classes

2023-06-20 16:41 UTC, xepozz commented on src/Classifier.php
> +        $this->dirs = $directory;
```suggestion
        $this->directories = $directory;
```

2023-06-21 07:44 UTC, xepozz requested changes

2023-06-21 07:44 UTC, xepozz commented on src/Classifier.php
> +            static fn($directory) => DIRECTORY_SEPARATOR === '\\' ? str_replace('/', '\\', $directory) : $directory,
Please check `DIRECTORY_SEPARATOR === '\\'` outside the function and use `str_replace` with array arguments:
```php

$directories = $this->directories;

$isWindows = DIRECTORY_SEPARATOR === '\\';
if ($isWindows) {
    $directories = str_replace('/', '\\', $this->directories);
}
```

2023-06-21 19:09 UTC, xepozz commented on src/Classifier.php
> +            static fn($directory) => DIRECTORY_SEPARATOR === '\\' ? str_replace('/', '\\', $directory) : $directory,
@rustamwin `str_replace` support batch replacing, no need to iterate and replace individually

2023-06-22 07:59 UTC, vjik requested changes

2023-06-22 07:59 UTC, vjik commented on src/Classifier.php
> +     * @var class-string
`class-string` is psalm-specific type

2023-06-22 07:59 UTC, vjik commented on src/Classifier.php
> +     * @return iterable<class-string>
```suggestion
     * @psalm-return iterable<class-string>
```

2023-06-22 07:59 UTC, vjik commented on src/Classifier.php
> +            if (!$reflection->isUserDefined()) {
Directory is required for search classes? If yes need modify constructor and make one parameter required.

2023-06-22 19:47 UTC, xepozz approved these changes

2023-06-25 16:46 UTC, vjik approved these changes

2023-06-26 04:19 UTC, merged